### ISSUE TITLE
Academia

### ISSUE THREAD

**Issue by JacobFischer** [siggame/MegaMinerAI-Game-Ideas#1]
Original pitch by Russley

The Galapagos creatures have evolved yet again! Their desire to advance and evolve eventually led to the creation of the first educational institute: The Galapagos Academy! Despite their efforts, their funding is being cut again. In order to cut costs, some under-performing departments will be cut from the academy.

You play as the head of your respective department. At your disposal you have undergrad ~~slaves~~ students and grad students. You must not only use grad students to research but you can only use what little funding is left to ~~buy~~ give grants and scholarships to grads and undergrads.

Undergrad:
* Cheap (Half as much as Grads)
* Fast (~2 move(s) per turn)
* Weak attack (~1 ATK)
* Weak defense (~2 HP)

Grad:
* Expensive (Twice as much as Undergrads)
* Cannot attack(?)
* High defense (~4HP)
* Slow (~1 move(s) per turn)
* Told to Research X turns
* If research is completed, gets X^2 performance.
* If research is not complete, gets no performance.

Walls:
* These walls are unmoveable, unpassable, undestroyable.
* They take up an edge rather than a square.
* Restricts movement along North, East, South, and/or West

Textbooks:
* Expensive
* Take up one tile
* When interacted with, does great amounts of healing.

Spawning:
* Far sides used for spawning
* Units cannot move into opponent's spawn
* Textbooks cannot be placed on a spawn

Win Conditions (in order):
* Departmental Performance
* Remaining Funding

**Comment by JeffreyStrahm** [comment]
I am a bit worried about the simplicity of this game. Not much of a theme to go off of.
