### ISSUE TITLE
Commerce

### ISSUE THREAD

**Issue by JacobFischer** [siggame/MegaMinerAI-Game-Ideas#25]
## Story

You are the owner of company Generic Evil Service Provider®. You've had a nice monopoly in your industry for a while. However, the most recent president, Dr. Roosevelt Jr., is cracking down on monopolies and plans to bust up some. But you have a plan, Another Generic Evil Service Provider® has a monopoly in _their_ industry so you need to buy politicians (legally called lobbying), and shift the trust busting on them!

## Objective

Buy more politicians than the enemy company, and have their company busted!

## Game Board

![commerce](https://cloud.githubusercontent.com/assets/1050503/22535309/dbe4309c-e8bf-11e6-817a-7229ca9fd617.jpg)

Commerce is a two player, turn based **card based** game; there's no grid or movement. Players (companies) manage decks of cards that represent a market, their company, and assets.

The game is heavily based on deck [deck building games][dgb]. Players each start with the same set of cards, and use those to buy new cards, thus building their deck _during_ gameplay. To remove the random concept of deck shuffling, players hand their decks to the opponent so they can arrange it however they want.

The table is split up into 3 sections, which could be thought of as arrays of cards. Each player's company gets a section where they play cards, and build their deck (company). In the center is the Market, which contains a set of special cards, as well as the politicians they need to buy to win the game.

## Cards

Cards (or assets in lore) represent the abilities of a company. The goal of the game is to buy politician cards, however _during gameplay politician cards are useless_. They are essentially a filler card that does nothing when played. This is a balancing act as when a player buys Politicians, they make their deck worse, rubber banding the other player.

So, players need to balance buying politicians with other cards. All the other cards have some abilities that make them more useful during gameplay. All the other cards have some actions they give the player that help them buy new cards.

### Actions

During a game players have a variable number of actions to perform during their turn:

* **Play**: The player takes a card and plays it in front of them, applying any effects
* **Trade**: The player discards a card from their hand to draw a card
* **Draw**: The player draws a card from their deck. If their deck is empty the enemy player is given the discard pile to arrange as they see fit for the new deck.
* **Money**: The player is given 1+ $ for the turn
* **Buy**: The player uses $ to buy a new card to their discard pile.
* **Destroy**: The player destroys a card in their hand or discard pile. That card is deleted from the game
* **Scandal**: The player causes a PR scandal for the enemy player, giving them a scandal card (which is essentially -1 politician at the end of the game).

A turn consists of the following:

1. Current Player draws 6 cards
2. Current Player starts with 1 Play, 1 Trade, and 1 Buy.
3. Current Player plays a card, many cards give +1 play back so they can "chain" cards.
4. Current Player eventually amassed enough money to buy a card from the market of their choosing.

### Possible Cards

We would develop a decent number of cards, and each game only allow a subset in. This is more randomness but it is applied equally to each player

_format_: **card_name** $card_cost: card_actions

#### Stocks

Stocks are the backbone of any company, They can be played for free and give money. Each player starts with 8 Class C stocks

* **Class C Stocks** $1: +1 Play, +$1
* **Class B Stocks** $3: +1 Play, +$2
* **Class A Stocks** $6: +1 Play, +$3

#### Politicians

The scumbags you are buying to win the game, but they are are useless and have no actions. They just clutter your deck! Each player starts with 4 **Corrupt Mayors**.

* **Corrupt Mayor** $2: _does nothing, worth 1 point at the end of the game_
* **Corrupt Representative** $5: _does nothing, worth 3 points at the end of the game_
* **Corrupt Senator** $8: _does nothing, worth 6 points at the end of the game_
* **Scandal** $0: _cannot be bought, instead nullifies the owner's lowest cost politician at the end of the game_

#### Corporate Assets

These are the bread and butter of a company. They all have varying effects, and a good company will find the ones that suit it to win

* **Insider Trading** $4: +1 Play, +2 Trades
* **Multiple Headquarters** $4: +3 Draws
* **Layoffs** $2: +1 Destroy
* **Offshore Account** $4: +$3
* **Price Fixing** $2: +$1, +2 Plays
* **Security Guards** $2*: +1 Draw, _If this card is in your hand you cannot gain scandals during your opponent's turn_
* **Media Control** $5: +1 Scandal
* **Day Trader** $2:  +2 Trades
* **Corporate Spy** $6: +1 Play, This card plays the highest cost card in the opponent's hand
* **Treasury Bonds** $4: +$3, +1 Trade _to your opponent next turn_
* **International Marketplace** $3: +1 Play, +1 Draw, +1 Trade
* **Research & Development** $3: +2 Plays, +1 Draw
* **Duopoly** $1: +1 Play, +1 Draw, +1 Draw _to your opponent_
* **Startup** $3: +1 Draw _per politician in your opponent's hand_, +1 Play
* **Social Media** $4: +$2, +1 Draw
* **Synergy** $2: +1 Draw _per other Synergy in play_, +1 Play

_and so on_

## Win conditions

When 4 stacks in the Market are empty, the game ends. Or if all the most expensive politicians get bought out the game ends. Otherwise at the end of 120 turns the game is terminated.

Winner is:

1. Player with the most politicians - scandals
2. If tied, the player with the least scandals
3. Else if tied, then the player with the larger deck
4. Else if tied, coin flip

## Analysis

Deck builders like [Dominion][dominion] are extremely well balanced because of the concept that _by doing the victory condition it is harder to keep doing it_, so they are self balancing. All tabletop deck builders rely on the randomness of shuffling, but we can actually capitalize on the speed of AIs to allow the opponent to shuffle instead. This means that Commerce is a **dual AI** game, where each AI needs to be capable of doing two tasks: playing and shuffling.

The most difficult part of and cary game is **balancing**. Luckily we can print of cards and test in real life to get the numbers down, and write AIs to play a lot and find the OP cards.

[dbg]: https://en.wikipedia.org/wiki/Deck-building_game
[dominion]: https://en.wikipedia.org/wiki/Dominion_(card_game)

**Comment by JeffreyStrahm** [comment]
Maybe next year, it is a good idea.
