### ISSUE TITLE
Plants

### ISSUE THREAD

**Issue by TehPers** [siggame/MegaMinerAI-Game-Ideas#48]
# Plants
Kill your opponent's Mother Plant before they take over your garden!
_[Original Game Suggestion](https://github.com/siggame/MegaMinerAI-Game-Ideas/issues/17)_

## Story
The year is 1986. Scores of people have fallen ill. Evacuations are underway. The world stands aghast: Chernobyl has occurred. It may be years before the full effects can even hoped to be grasped.

But none of that matters to you! You are a simple plant, and you have bigger concerns than the horrible death and destruction surrounding your garden. In fact, besides your own newfound sentience, there's only one other effect of the nuclear fallout that you really care about: there's another newly sentient plant breathing your fallout-saturated air. And he's/she's/it's sitting in your garden. As the world around you struggles to come to terms with the horror that is Chernobyl, you and your plant enemy must spawn armies of plant underlings to wage war over a four- by six-foot patch of dirt. But it's your four- by six-foot patch of dirt, dang it.

_(Modified from original to use plants instead of weeds)_

## Win Conditions
Kill the opponent's Mother Plant.
__If the turn limit has been reached, victory will be decided with these conditions:__
1. The player whose Mother Plant has the fewest rads
2. The player who has more plants
3. The player with the fewest total rads among their plants
4. The player with the highest total strength among their plants
5. Coin toss

### The Garden
Both players start with a Mother Plant on opposite sides of the garden. The garden is 32x20 (smaller than the original), and will have toxic pools spread throughout it. 
### Toxic Pools
Each turn, the toxic pool is drained equal to the number of plants inside of it. Toxic pools increase a plant's rads each turn the plant is in the pool, with the exception of Soakers. Instead, Soakers use the toxic pool to buff nearby friendly plants.
### Plants
Each plant has a spore cost, a base strength, a current strength, a range, and a max number of rads. They radiate at the end of their owner's turn.

| Name | Cost | Max Rads | Base Strength | Range | Abilities |
|----|----|----|----|----|----|
| __Mother__ | N/A | Very High | N/A | High | Each player starts with one. Plants can be spawned in range. Cannot be uprooted. |
| __Spawner__ | High | Medium | N/A | Medium | Plants can be spawned in range. Cannot be uprooted. |
| __Choker__ | Low | Low | Medium | Low | Damages enemy plants in range equal to its strength. _(Radiate Ability)_ |
| __Titan__ | Medium | High | Low | High | Damages enemy plants in range equal to its strength. _(Radiate Ability)_ |
| __Aurelia__ | Medium | Medium | Medium | Medium | Damages enemy plants in range equal to its strength. _(Radiate Ability)_ |
| __Bumbleweed__ | Medium | Medium | Low | Low | Removes rads from friendly plants (except Bumbleweeds) equal to its strength. Affected plants lose strength relative to the rads they lose. Note: This means they temporarily heal more when damaged. _(Radiate Ability)_ |
| __Soaker__ | Medium | Low | Low | High | Does not take damage from toxic pools. If in a toxic pool, increases strength of friendly plants in range equal to its strength. Note: This means they temporarily provide a stronger buff when damaged. _(Radiate Ability)_ |
### Spores
Spores are used to spawn new plants. Players start with a certain number of spores. Each turn, they gain spores relative to the total cost of the plants they have. A player with a higher total cost will gain fewer spores. This means that players who are behind will be able to spawn plants faster.
### Rads
Plants deal damage to each other in the form of adding rads to them. Plants which reach their maximum number of rads will die. However, when a plant gets rads, their strength increases temporarily depending on how many rads they get. This will lead to faster battles between plants.

Bumbleweeds are the only plants capable of removing rads. When they radiate, every friendly plant in range of a Bumbleweed (except other Bumbleweeds) will lose rads equal to a fraction of the Bumbleweed's strength. This also temporarily decreases the strength of the affected plants.
### Radiating
Each plant radiates at the end of their owner's turn. This means different things for different plants.
### Strength
After a plant radiates, if a plant's strength is higher than its base strength, it decreases. If its strength is lower than its base strength, it increases. This means that changes in strength are temporary. The amount they change is relative to the difference between its strength and its base strength.
### Uprooting (Movement)
All plants except Mother plants and Spawner plants can be uprooted. This allows them to move to anywhere in range, but has a cooldown relative to the distance they move.
### Range
Range is calculated using the Euclidean distance formula, so it will be a circle. Helper functions should be included to allow competitors to easily see if a tile is in range of a plant.

![image](https://user-images.githubusercontent.com/2214247/35641167-09a15684-0685-11e8-9c07-bf2075119d08.png)
_(Original Plants image)_

**Comment by JeffreyStrahm** [comment]
It is going to be helpful to players that they only need to use targeting to spawn and move. This is definitely a wide build type of game. Nothing that I can see needs to be changed.
