### ISSUE TITLE
Wizards

### ISSUE THREAD

**Issue by SethKitchen** [siggame/MegaMinerAI-Game-Ideas#54]
I'm here to be something original instead of these grid based, birds-eye, multi-unit games where there is no customization for the AI. Let's have one with a side-view, where each AI is a single unit with custom powers from a pool (think smash bros). But we fix the problem of real-time, by only allowing one spell per turn and limited movement. My game idea is a revamping/AI version of the classic Arcanists. 

**Game In Action**

[https://www.youtube.com/watch?v=RWBPVmjqxqA](url)

![image](https://user-images.githubusercontent.com/9014645/45176517-d71db980-b1d5-11e8-8b37-dd5b074f8c00.png)

![image](https://user-images.githubusercontent.com/9014645/45176538-ed2b7a00-b1d5-11e8-971e-b4ff6d5fedc6.png)

**Goal:** 1) Destroy the other Wizard(s) 2) Be the one with the most health at the end. 3) Caused the most damage. 4) Least times falling off land  5) Coin Flip

So Sig-Game would come up with a list of 60 or so spells that AIs would select 16 or so from during Round 1. They would not be able to swap them during the game or see their opponent's spells (until 
they used it).

Instead of grid moving, we implement hop, step left, and step right using physics (ie hop gives an initial velocity of 5px/s then we use vt+0.5at^2 to have them land). The advantage of this is depending on the terrain (friction or terrain is higher than unit height) some AIs may not be able to jump, but it's easy to code because you just do player.hop(). Usually you'd want to hop with a direction at a certain time so we could have hopright(.5) which means at .5 seconds into the jump do a right step. Hop would be 1 movement. Hopright would be 2 movement. We can give them like 5 or 10 movement per turn. If an AI cannot get over an obstacle, they can use a spell to clear the way.

Once they hop and step their way over to the opponent - the use a spell which does damage and knock-back.  Some example spells are given below.  If an AI is knocked off the map they immediately take a lot of damage and are teleported back onto the map (maybe the center?).

Spells can take a certain number of rounds to be used, may have to be recharged, may have limited number of uses, etc. This game requires a bunch of balancing beforehand, but will be much more fun for competitors who will love the customization. Devs will love it because they can implement whatever spells they want and someone will balance it so it's fair. Arcanists is my favorite game of all time.

**Map Inspiration**

![image](https://user-images.githubusercontent.com/9014645/45177189-df76f400-b1d7-11e8-9c00-379fb6a03097.png)

![image](https://user-images.githubusercontent.com/9014645/45177214-f289c400-b1d7-11e8-8d34-08a7efe2ff5b.png)

 VOLCANOS APPEAR UNDER THE MAP AT RANDOM TIMES AND BLAST FIRE

![image](https://user-images.githubusercontent.com/9014645/45177231-fcabc280-b1d7-11e8-9cae-7cd4b98dc76e.png)

METEORS APPEAR FROM THE SKY AT RANDOM TIMES AND DEAL DAMAGE TO A SINGLE AREA

![image](https://user-images.githubusercontent.com/9014645/45177303-354b9c00-b1d8-11e8-8ed9-96cc52010aa4.png)

LIGHTNING SPRAYS FROM THE SKY AT RANDOM TIMES AND DEAL DAMAGE TO MANY SMALL LOCATIONS

![image](https://user-images.githubusercontent.com/9014645/45177321-3c72aa00-b1d8-11e8-8511-be116c4412d6.png)

A HEALING LIGHT APPEARS FROM THE SKY AND GIVES HEALTH TO A SINGLE AREA

**Spell Inspiration**
Book of Arcane:
![image](https://user-images.githubusercontent.com/9014645/45178439-4944cd00-b1db-11e8-86ea-f89545f12728.png)

![image](https://user-images.githubusercontent.com/9014645/45224882-b9595e80-b280-11e8-8fe7-e2cd632f88d7.png)

![image](https://user-images.githubusercontent.com/9014645/45224906-c8d8a780-b280-11e8-9cf4-f4abc1e169d6.png)

Book of Storm:
![image](https://user-images.githubusercontent.com/9014645/45224826-975fdc00-b280-11e8-8c09-2d11b77b9c3f.png)

![image](https://user-images.githubusercontent.com/9014645/45224982-fe7d9080-b280-11e8-8743-929b92f3b1b3.png)

![image](https://user-images.githubusercontent.com/9014645/45225001-0e957000-b281-11e8-842c-d3b7eaaf414c.png)

Book of Fire:

![image](https://user-images.githubusercontent.com/9014645/45232449-0cd5a780-b295-11e8-9a8f-9127f837a898.png)

![image](https://user-images.githubusercontent.com/9014645/45232473-2971df80-b295-11e8-8c5c-dd4dc9bddad4.png)

Book of Stone:

![image](https://user-images.githubusercontent.com/9014645/45232509-48707180-b295-11e8-9b39-3ea5c3597801.png)

![image](https://user-images.githubusercontent.com/9014645/45232523-545c3380-b295-11e8-9d40-dcddd325eaeb.png)

![image](https://user-images.githubusercontent.com/9014645/45232539-6047f580-b295-11e8-8da9-27d1b8b6575b.png)

Book of Frost:

![image](https://user-images.githubusercontent.com/9014645/45232591-85d4ff00-b295-11e8-9e11-a6b9589a2f7f.png)

![image](https://user-images.githubusercontent.com/9014645/45232605-8ff6fd80-b295-11e8-9135-ce6434d6a2f3.png)

Book of Underdark:

![image](https://user-images.githubusercontent.com/9014645/45232619-a56c2780-b295-11e8-8e01-039ab76c0726.png)

![image](https://user-images.githubusercontent.com/9014645/45232636-b2891680-b295-11e8-8196-924e6a66f099.png)

![image](https://user-images.githubusercontent.com/9014645/45232640-bb79e800-b295-11e8-8042-a8a6fa6df353.png)

Book of Overlight:

![image](https://user-images.githubusercontent.com/9014645/45232655-d3516c00-b295-11e8-8aa9-ac483329ea5a.png)

![image](https://user-images.githubusercontent.com/9014645/45232666-de0c0100-b295-11e8-8953-9fdd8891a64a.png)

![image](https://user-images.githubusercontent.com/9014645/45232677-e6fcd280-b295-11e8-9112-01dec37bce0e.png)

Book of Nature:

![image](https://user-images.githubusercontent.com/9014645/45232718-0431a100-b296-11e8-8dcd-399a59a9e416.png)

![image](https://user-images.githubusercontent.com/9014645/45232762-2deac800-b296-11e8-80c3-a896bf8c6fc8.png)

![image](https://user-images.githubusercontent.com/9014645/45232778-3d6a1100-b296-11e8-968e-c44dcfd32520.png)

Book of Seas:

![image](https://user-images.githubusercontent.com/9014645/45232811-55da2b80-b296-11e8-84c1-3a636116625a.png)

![image](https://user-images.githubusercontent.com/9014645/45232816-5f639380-b296-11e8-8588-34a2314a089e.png)

![image](https://user-images.githubusercontent.com/9014645/45232820-67233800-b296-11e8-91f1-7aa2cbab1887.png)

Book of Cogs: 

![image](https://user-images.githubusercontent.com/9014645/45232836-7d30f880-b296-11e8-8852-b7bc614966ba.png)

![image](https://user-images.githubusercontent.com/9014645/45232852-8de16e80-b296-11e8-9028-497e89d3f55a.png)

![image](https://user-images.githubusercontent.com/9014645/45232861-976ad680-b296-11e8-9ffa-0c67b676ef26.png)

**Comment by JeffreyStrahm** [comment]
My biggest fear with this is programming every single spell. It would take forever. Not to mention the complex movement.

**Comment by SethKitchen** [comment]
The idea is we don't implement all the spells -- It should be interesting to Devs because they can implement whatever spells they like -- they should want to do a lot of spells

**Comment by SethKitchen** [comment]
https://gamedev.stackexchange.com/questions/93511/how-can-i-generate-a-2d-mountain-landscape-procedurally

**Comment by JeffreyStrahm** [comment]
I do have a few other concerns, the list of spells will probably give coders choice paralysis.
Also, I want to point out that while this game is original, originality is not a good reason to select any game.
