### ISSUE TITLE
JavaCrypt

### ISSUE THREAD

**Issue by NathanFambrough** [siggame/MegaMinerAI-Game-Ideas#56]
(WIP: Rough draft written on phone)

Story: You’re a ragtag group of adventurers who seek to slay the evil Lich in the bottom of the crypt and claim his riches for your own. Unfortunately for you, you’re not the only one after this mark. Another team approaches your bounty from a separate staircase, and there isn’t enough gold in this dungeon for the two of you. 

Game elements:
Respawning enemies
Grid based gameplay
“Boss” monster
Party units that regenerate?
PvPvE gameplay

Units:
Player
-Warrior
-Barbarian
-Priest
-Rogue
-Wizard/Archer

Enemy:
-Spider
-Ghost
-Skeleton
-Lich

Priests heal.
Wizards, archers, and the Lich can attack at range. 
Barbarian has higher attack, Warrior has higher HP and Defense
Rogues can carry more loot. 
Ghosts can chase targets through walls. 
The monsters respawning is tied to the Lich. It dies, monsters stop respawning.

Win condition: Whomever gets the most loot out of the dungeon(certain threshold?) wins. Killing the Lich is beneficial(cash bonus goes to the team who gets the killing blow) but not necessary to winning. 

========Draft 2=======

### **Story:** 
You’re a ragtag group of adventurers who seek to slay the evil Lich in the bottom of the crypt and claim his riches for your own. Unfortunately for you, you’re not the only one after this mark. Another team approaches your bounty from a separate staircase, and there isn’t enough gold in this dungeon for the two of you. 

### **Victory Condition:**
Whoever gets the most loot out of the dungeon(Either by passing a certain threshold or a turn count) wins. While the story implies that killing the Lich ends the game, it only provides a sizable cash bonus.

### **Map:**
The map is a labyrinthine catacomb, with rooms branching off of halls and monsters scattered across its entirety. In the far back is the Lich's room, and two exits from the catacomb exist on opposite sides of the map, equidistant from the Lich's room.

### **Units:**
Five unit types are available to the user _(Suggestion: Either require them to decide team composition before the match starts, or provide one of each)_

**Priest**
--HP: Low
--Attack: Low
--Effect: Can heal a unit for 10 points of damage each turn, or use an AoE heal for 5 points once every three turns.

**Rogue**
--HP: Low-Medium
--Attack: Medium
--Effect: Inflicts higher damage to an enemy if 'behind' them. Also has the highest carry capacity for loot.

**Paladin**
--HP: Medium-High
--Attack: Medium-High
--Effect: Has high aggro and takes reduced damage.

**Wizard**
--HP: Low
--Attack: High
--Effect: Can attack at range, throwing fireballs.

**Barbarian**
--HP: High
--Attack: High
--Effect: Nothing. Purely a heavy hitter.

In the event a character dies, they lose a portion of the loot they were carrying and 'respawn' back at their original entrance.

Four types of monsters exist, and of them, three respawn.

**Spider**
--HP: Medium
--Attack: Low

**Skeleton**
--HP: Medium
--Attack: Medium
--Effect: Takes damage from the Priest's heal.

**Ghost**
--HP: Low
--Attack: Medium
--Effect: Ghosts have no collision(Might make it so that there's a cap of 1 ghost per tile), and can aggro through walls. They also take damage from the Priest's heal.

**Lich**
See below.

### The Boss

The Lich is a powerful unit, being able to attack at range like the Wizard, has a lot of health, and a respectable level of attack. But moreover, as he is the boss of the dungeon, he has certain things going for him.

The first time he takes damage, all monsters within a X grid radius immediately aggro the room.
Once he drops below 75% HP, three skeletons spawn in the room to support the Lich.
Once he drops below 50% HP, several ghosts spawn in the walls surrounding the room, including two surrounding the exit to the room to go after any tactically placed ranged attackers.
Once he drops below 25% HP, his attack increases.
Once he drops dead, the character who dealt the finishing blow gets a 500 gold bounty, and a 200 gold bounty is divided among all characters based on damage each contributed to the battle.

Oh, and as an undead, he also takes damage from the Priest's heal.

**Comment by TwinNumberOne** [comment]
hey, what is the Koch? I think you have a typo.

**Comment by TwinNumberOne** [comment]
hey, what is the difference between the archer and the wizard?

**Comment by StaneCobalt** [comment]
JavaCrypt... where the Garbage Collector sends everything to die.

**Comment by JeffreyStrahm** [comment]
The only problem I can see with this is how we can add player interaction, instead of it being effectively separate games.

**Comment by JeffreyStrahm** [comment]
Re-opening because he said he is going to refine it for the next mega-miner.

**Comment by TwinNumberOne** [comment]
doesn't the barbarian seem out of place? with the wizard you can optimize what they hit to make sure the most enemies die, the paladin needs to be placed so that its allies can maximize their attacks, the priest will mainly just be healing the paladin or kill stealing a mob, the rouge while getting higher dmg from behind has nothing for potential ago so it will rely on the paladin to give it targets, and then the barbarian I guess runs intercept for anything that ignores the paladin? or just goes up and beats on enemies... Also from what I am seeing both players will just rush the lich or try and steal the gold from the other player. Also all in all no agro reduction for the rogues? how will agro work in this game?
