### ISSUE TITLE
Archmage

### ISSUE THREAD

**Issue by JeffreyStrahm** [siggame/MegaMinerAI-Game-Ideas#58]
You are a grand sorcerer who cannot remember his spells to save his life unless you read them, except for one simple spell. Your arch nemesis has the same problem, which is why you memorized the library shuffle spell! Sadly your arch nemesis had the same idea and mixed up your library! Engage in an epic duel where only the most skills mage will win and expand your collection while you're at it.

Gameplay:
Each turn player get 5 mana. They will gain 1 more if below half health, and 1 more if below a quarter health. The only way this can go higher is card effects. They draw the top 10 cards from their deck and place them into their hand and may play any cards they want. The can hold a maximum of 15. Every card costs x mana to play. They also start with 100 HP each. Finally, they each have an income of 10 gold per round. Each player will discard their entire hand after each turn and draw a new one at the beginning of each turn unless otherwise specified, aka keep x card effects. Each sorcerer starts off with a base deck of:

3 x Minor heal: 1 mana, restore 5 HP
3 x Minor burn: 1 mana, deal 5 HP
1 x Spell wall: 1 mana, summon a taunt creature that has 1 HP and 0 Atk. 
1 x dismiss (Summon only): 1 mana, deal 1 HP to all creatures on the field.
2 x manaMarket: 1 mana, gain 5 gold.

There is a maximum of 10 creatures allowed on the field.

Each player may also go to the store and purchase cards to add to their deck, they may do this before drawing. All cards are presented as options which varying costs based on the power of the card. The following libraries are:
summoner: get spells specialized in summoning creatures.
Arcane: get spells specialized in dealing damange.
restoration: get spells specialized in healing.
Divine: get spells specialized in buffs.
Infernal: get spells specialized in debuffs.
Null: Get spells specialized in canceling or nullifying.
other: Remove useless spells from your library at the cost of 5 gold per, or purchase a manamarket at a cost of 5 gold per.

Once every 5 turns a player may turn in their entire library and get a full refund for all purchased cards. The must immediately reshuffle their deck, and ends their turn. Base cards are not removed when a player uses this, including base cards added later.

Note: whenever a player shuffles a deck, the opponent decides the order of the cards.
Note2: A player will always know the order of their entire deck. (AKA they know their next hands)

Cards can have effects similar to the following:
Creature effects:
Taunt: must be attacked before any non-taunt creatures can be attacked. Creatures cannot attack a player while a taunt creatures exists.
Regen: +1 HP end of the turn.
Fast: can attack upon being summoned
Coward: cannot be attacked by summons, cannot receive the taunt enchantment.
Fading: every turn the creature loses 1 HP (cannot have regen)
First strike: only takes damage if the opponent lives it's attack,
Death touch: kills any summon it interacts with, regardless of first strike. (still takes damage)
(Creatures should also be able to be summoned with debuffs as additional options)

Cards: (should keep this list small for easy ability for players to value cards)
Draw: draws a card
Restore: heals x HP
Damage: does x damage to something
Summon only: effects only summons. (debuff cards have to have this)
player only: can only effect the opposing player
Charged: gain x extra mana next turn.
Draining: gain x less mana next turn.
Debuff/buff: attached an effect to a monster.
(example, apply 2x the current poisoned on the target creature)

Effects:
poisoned: lose 1 hp per round (stack-able). Reduces by 1 each turn. Applies at the end of that creatures turn.
poisoner: apply 1 additional poisoned to any touched creatures. (stack-able)
death touch: kills any summon interacting with this summon
frozen: can't act next turn.
Enchanted: can't act.

These are just ideas. With the ability to change libraries it should be a very wide game for people to dig at with an interesting mana selling system. It could be possible to let player build their cards using a library of effects.

**Comment by JeffreyStrahm** [comment]
May replace this later with a different idea.

**Comment by SethKitchen** [comment]
YES SOMETHING BESIDES GRID BASED! Hearthstone port :D love it

**Comment by JeffreyStrahm** [comment]
Due to the complexity of coding this game or coding an AI for it, I will close it and write another as a suggestion.
