### ISSUE TITLE
Inertia

### ISSUE THREAD

**Issue by firegodjr** [siggame/MegaMinerAI-Game-Ideas#62]
Two AI cars race against each other on identical tracks. The tracks contain hazards such as rough patches, oil spills, collectibles, etc. Your car can go as fast as you'd like, however, the faster you go the harder it is to turn to avoid hazards, so AI must compensate for speed and distance to hazards. First car to the end of the track wins.

**Comment by TwinNumberOne** [comment]
Dude, what types of collectibles? like are we talking green shells, speed boosts, or are we talking 1 of 5 secret things hidden on the map collect them all for achievement (aka traditional collectibles). Also by identical tracks do you mean they are racing on two separate tracks meaning they don't interact with each other? no car collisions?
